project_id = "vrpnrpokooqjmojyjzaz"

[functions.predict-wage-ml]
verify_jwt = false

[functions.predict-wage-ml-v2]
verify_jwt = false

[functions.assess-wage]
verify_jwt = false

[functions.assess-batch]
verify_jwt = true
